### ISSUE TITLE
Latest data query: adding field for time at which a measurement was logged

### ISSUE THREAD

**Issue by af-a** [ropod-project/black-box#1]
## Problem Description
The black box logs variable measurements with a timestamp that represents the current time (time at which the message is created by the black box).
However for LATEST_DATA_QUERY responses, it would be better if it provides the timestamp of when the value was actually logged, for the plotJuggler plugin which streams black box data .

## Suggested Solutions
- In the query interface: adding a message field that represents the time point at which the value was logged by the black box.

**Comment by alex-mitrevski** [comment]
The timestamp is actually already returned. The items in [`dataList`](https://github.com/ropod-project/black-box/blob/master/pybb/black_box/query_interface/query_interface.py#L94) are always pairs in which the second element is a measurement and the first element is the timestamp at which the measurement was taken. I had to look at the code to remind myself of this.
